/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThesisRouteImport } from './routes/thesis'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectorsSectorRouteImport } from './routes/sectors.$sector'

const ThesisRoute = ThesisRouteImport.update({
  id: '/thesis',
  path: '/thesis',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsSectorRoute = SectorsSectorRouteImport.update({
  id: '/sectors/$sector',
  path: '/sectors/$sector',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/ecosystem': typeof EcosystemRoute
  '/journal': typeof JournalRoute
  '/thesis': typeof ThesisRoute
  '/sectors/$sector': typeof SectorsSectorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/ecosystem': typeof EcosystemRoute
  '/journal': typeof JournalRoute
  '/thesis': typeof ThesisRoute
  '/sectors/$sector': typeof SectorsSectorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/ecosystem': typeof EcosystemRoute
  '/journal': typeof JournalRoute
  '/thesis': typeof ThesisRoute
  '/sectors/$sector': typeof SectorsSectorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/ecosystem'
    | '/journal'
    | '/thesis'
    | '/sectors/$sector'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/ecosystem'
    | '/journal'
    | '/thesis'
    | '/sectors/$sector'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/ecosystem'
    | '/journal'
    | '/thesis'
    | '/sectors/$sector'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  EcosystemRoute: typeof EcosystemRoute
  JournalRoute: typeof JournalRoute
  ThesisRoute: typeof ThesisRoute
  SectorsSectorRoute: typeof SectorsSectorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thesis': {
      id: '/thesis'
      path: '/thesis'
      fullPath: '/thesis'
      preLoaderRoute: typeof ThesisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors/$sector': {
      id: '/sectors/$sector'
      path: '/sectors/$sector'
      fullPath: '/sectors/$sector'
      preLoaderRoute: typeof SectorsSectorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  EcosystemRoute: EcosystemRoute,
  JournalRoute: JournalRoute,
  ThesisRoute: ThesisRoute,
  SectorsSectorRoute: SectorsSectorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
